# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72f4976feaf6682b16a0a8dec900baaf1734bc68570f957a1f1def776779183fde1e15ac0037cec4f6b193a44e63a8c174b8bd4917341c246e154f2bad6f9b0c

test:
  secret_key_base: a394cdcf90c90209509a98ef6418bb2a64f29822703fb4ffed20575216dd131af6f625c219ba778efdecdc8efc742e3ec1a11092f917e3817511a2836762523e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
